export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILED = 'GET_SKILLS_FAILED';

export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAILED = 'UPDATE_SKILL_FAILED';

export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAILED = 'DELETE_SKILL_FAILED';
